# Generated by Django 4.0.1 on 2022-01-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0003_alter_superhero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
